import Link from "next/link";
import { ReactNode } from "react";
const nav = [
  { href:"/", label:"Home" },{ href:"/interactive-pets", label:"Interactive Pets" },{ href:"/ai-robotic-pets", label:"AI & Robotic Pets" },{ href:"/best-for-seniors", label:"Best for Seniors" },{ href:"/compare", label:"Compare" },{ href:"/reviews", label:"Reviews" }
];
export function SiteHeader() {
  return <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="container-shell flex items-center justify-between gap-6 py-4"><Link href="/" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-900 text-lg text-white">🐾</div><div><div className="text-sm font-semibold text-slate-900">Smart Pets Marketplace</div><div className="text-xs text-slate-500">Interactive & AI companion guides</div></div></Link><nav className="hidden items-center gap-6 lg:flex">{nav.map((item)=><Link key={item.href} href={item.href} className="text-sm font-medium text-slate-700 transition hover:text-slate-900">{item.label}</Link>)}</nav><Link href="/compare" className="btn-primary hidden sm:inline-flex">Shop Top Picks</Link></div></header>;
}
export function StickyCompareBar() {
  return <div className="fixed bottom-4 left-0 right-0 z-40"><div className="container-shell"><div className="mx-auto flex max-w-3xl items-center justify-between gap-4 rounded-full border border-slate-200 bg-white px-4 py-3 shadow-soft"><div><p className="text-sm font-semibold text-slate-900">Need a faster decision?</p><p className="text-xs text-slate-600">Compare comfort, ease of use, and price in one view.</p></div><Link href="/compare" className="btn-primary shrink-0">Open Compare</Link></div></div></div>;
}
export function SiteFooter() {
  return <footer className="border-t border-slate-200 bg-white"><div className="container-shell py-12"><div className="grid gap-10 md:grid-cols-3"><div><p className="text-base font-semibold text-slate-900">Smart Pets Marketplace</p><p className="mt-3 max-w-sm text-sm leading-7 text-slate-600">A cleaner way to compare companion-style interactive pets and AI & robotic pets for seniors, families, and gift buyers.</p></div><div><p className="text-sm font-semibold text-slate-900">Explore</p><div className="mt-4 space-y-3 text-sm text-slate-600"><Link href="/interactive-pets" className="block hover:text-slate-900">Interactive Pets</Link><Link href="/ai-robotic-pets" className="block hover:text-slate-900">AI & Robotic Pets</Link><Link href="/best-for-seniors" className="block hover:text-slate-900">Best for Seniors</Link></div></div><div><p className="text-sm font-semibold text-slate-900">Affiliate note</p><p className="mt-4 text-sm leading-7 text-slate-600">Replace placeholder links with your affiliate URLs and add a visible affiliate disclosure before launch.</p></div></div></div></footer>;
}
export function PageShell({ children }: { children: ReactNode }) { return <><SiteHeader /><main>{children}</main><SiteFooter /><StickyCompareBar /></>; }
