// Re-export shim — do not edit by hand.
// Source of truth: app/best-for-memory-care/scores.ts (auto-generated by generate_ranked_list.py).
// This file exists so customize-rankings.tsx can import without path changes.
export {
  SCORES as MEMORY_CARE_SCORES,
  TOP_SCORE_IN_GROUP,
} from "../app/best-for-memory-care/scores";
export type {
  BestForScoreRow as MemoryCareScoreRow,
} from "../app/best-for-memory-care/scores";
