import { PageShell } from "@/components/layout";
import { BestForCard } from "@/components/best-for-card";
import { ScoreGauge, ScoreBar } from "@/components/score-gauge";
import {
  IconSparkleClean, IconDurability, IconUsers, IconShieldCheck,
  IconBattery, IconPrivacy, IconBrain, IconHeartHands, IconAward,
  featureIcon, StarRating,
} from "@/components/best-for-icons";
import { products } from "@/components/site-data";
import Link from "next/link";

// ── Auto-generated data (regenerated by generate_ranked_list.py) ─────────
import {
  SPREADSHEET_UPDATED, TOP_SCORE_IN_GROUP, TOP_PICK_RAW_SCORE, TOP_PICK_PERCENT,
  RANKED_SLUGS, SCORE_PERCENT, RUNNER_NOTES, TOP_PICK_CRITERIA_DATA, JSON_LD,
} from "./page-data";
import { SCORES } from "./scores";

// ── Icon mapping — update labels to match TOP_PICK_CRITERIA_DATA in page-data.ts ─
const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  "Cleanability": IconSparkleClean, "Durability": IconDurability,
  "Caregiver Burden": IconUsers,    "Safety Risk": IconShieldCheck,
  "Charging Convenience": IconBattery, "Privacy Risk": IconPrivacy,
  "Dementia Suitability": IconBrain,
  // TODO: add icons for any criteria specific to this list
};
const TOP_PICK_CRITERIA = TOP_PICK_CRITERIA_DATA.map((c) => ({
  ...c, Icon: ICON_MAP[c.label] ?? IconSparkleClean,
}));

// ── TODO: Review these bullets when the top pick changes ─────────────────
// Must be grounded in locked rubric anchors — never invented marketing claims.
const WHY_TOP_PICK_BULLETS: { label: string; note: string }[] = [
  // TODO: populate from top pick's highest-scoring criteria
];

export default function BestForPage() {
  const ranked = RANKED_SLUGS
    .map((slug) => products.find((p) => p.slug === slug))
    .filter(Boolean) as NonNullable<(typeof products)[number]>[];
  const topPick = ranked[0];
  const runners = ranked.slice(1);

  return (
    <PageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON_LD }} />

      {/* Hero */}
      <section className="bg-purple-100 py-8 sm:py-10">
        <div className="container-shell">
          <div className="flex items-start gap-4">
            <div className="hidden sm:flex h-20 w-20 shrink-0 items-center justify-center rounded-full bg-white text-purple-600 shadow-soft">
              <IconHeartHands className="h-10 w-10" />
            </div>
            <div>
              <p className="eyebrow">Best For Rankings</p>
              <h1 className="mt-1 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">Best Pets for Seniors in Memory Care Facilities</h1>
              <p className="mt-2 max-w-2xl text-base font-medium leading-7 text-slate-700">
                {/* TODO: add description */}
              </p>
              <p className="mt-2 inline-flex items-center gap-2 text-xs font-semibold text-trust-700">
                <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-trust-500 text-white text-[10px]">✓</span>
                Ratings from Verified Sources · Updated {SPREADSHEET_UPDATED}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* See app/best-pets-for-seniors-in-memory-care-facilities/page.tsx for the full Best For page template.
          TODO: add Top Pick card, Why Top Pick, How We Ranked, Customize, Also Ranked sections. */}

      {/* Also Ranked */}
      <section className="py-4 sm:py-5 bg-white">
        <div className="container-shell">
          <h2 className="text-xl font-extrabold tracking-tight text-slate-900 sm:text-2xl">Top Picks</h2>
          <p className="mt-0.5 text-sm text-slate-700">Ranked by weighted criteria for this audience.</p>
          <div className="mt-2 grid gap-2.5 sm:grid-cols-2 xl:grid-cols-5">
            {ranked.map((product, i) => (
              <div key={product.slug} className="flex flex-col">
                <p className="mb-1 text-xs font-bold uppercase tracking-wide text-slate-500">#{i + 1} Ranked</p>
                <BestForCard product={product} note={RUNNER_NOTES[product.slug]} className="flex-1"
                             scorePercent={SCORE_PERCENT[product.slug]} accentColor="text-purple-600" />
              </div>
            ))}
          </div>
          <div className="mt-4 border-t border-purple-200 pt-3 text-center">
            <Link href="/best-pets-for-seniors-in-memory-care-facilities/scoring" className="text-sm font-semibold text-trust-600 underline underline-offset-4 hover:text-trust-800">Show detailed scoring results →</Link>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
