import { PageShell } from "@/components/layout";
import Link from "next/link";
// AUTO-GENERATED data — regenerated by generate_ranked_list.py
import { WEIGHTS, ROWS, GENERATED_DATE, type ScoreKey } from "./scoring-data";

function ScoreCell({ value, reversed }: { value: number; reversed: boolean }) {
  // Colour-code: 5 = best (green tint), 1 = worst (neutral), mid = default.
  const isTop = value === 5;
  const isLow = value <= 2;
  return (
    <td
      className={`border border-trust-200 px-3 py-2 text-center text-sm font-semibold ${
        isTop ? "bg-trust-50 text-trust-700" : isLow ? "text-slate-400" : "text-slate-700"
      }`}
    >
      {value}
    </td>
  );
}

export default function MemoryCareScoring() {
  return (
    <PageShell>
      <section className="section-pad">
        <div className="container-shell">
          <div className="mb-8">
            <Link
              href="/best-for-memory-care"
              className="text-sm font-semibold text-trust-600 hover:underline"
            >
              ← Back to rankings
            </Link>
          </div>

          <p className="eyebrow">Detailed Scoring</p>
          <h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
            Best for Seniors in Memory Care Facilities — Top 5 Results
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">
            All scores are 1–5. For criteria marked{" "}
            <span className="font-semibold text-slate-800">(↑ higher = better outcome)</span> a score of 5
            means the lowest caregiver burden, lowest privacy risk, or lowest safety risk respectively.
            Generated {GENERATED_DATE}. Tiebreaker order: Score → Customer Rating → Visual Contrast → Review Count.
          </p>

          <div className="mt-8 overflow-x-auto rounded-2xl border border-trust-200 shadow-soft">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="bg-trust-50">
                  <th className="border border-trust-200 px-3 py-3 text-left font-semibold text-slate-900 whitespace-nowrap">
                    Rank
                  </th>
                  <th className="border border-trust-200 px-3 py-3 text-left font-semibold text-slate-900">
                    Product
                  </th>
                  <th className="border border-trust-200 px-3 py-3 text-right font-semibold text-slate-900 whitespace-nowrap">
                    Price
                  </th>
                  <th className="border border-trust-200 px-3 py-3 text-right font-semibold text-slate-900 whitespace-nowrap">
                    Rating
                  </th>
                  <th className="border border-trust-200 px-3 py-3 text-center font-bold text-trust-900 whitespace-nowrap">
                    Overall
                  </th>
                  {WEIGHTS.map((w) => (
                    <th
                      key={w.key}
                      className="border border-trust-200 px-3 py-3 text-center font-semibold text-slate-700 whitespace-nowrap"
                    >
                      {w.label}
                      <br />
                      <span className="text-xs font-normal text-slate-500">{w.weight}</span>
                      {w.reversed && (
                        <>
                          <br />
                          <span className="text-[10px] font-normal text-trust-600">↑ higher = better</span>
                        </>
                      )}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {ROWS.map((row, i) => (
                  <tr key={row.rank} className={i % 2 === 0 ? "bg-white" : "bg-cream-50"}>
                    <td className="border border-trust-200 px-3 py-3 font-bold text-trust-700 whitespace-nowrap">
                      #{row.rank}
                    </td>
                    <td className="border border-trust-200 px-3 py-3">
                      <p className="font-semibold text-slate-900">{row.product}</p>
                      <p className="text-xs text-slate-500">
                        {row.manufacturer} · {row.animal} · {row.priceCategory}
                      </p>
                    </td>
                    <td className="border border-trust-200 px-3 py-3 text-right text-slate-700 whitespace-nowrap">
                      {row.price}
                    </td>
                    <td className="border border-trust-200 px-3 py-3 text-right text-slate-700 whitespace-nowrap">
                      ★ {row.rating}
                      <br />
                      <span className="text-xs text-slate-500">({row.reviews} reviews)</span>
                    </td>
                    <td className="border border-trust-200 px-3 py-3 text-center font-bold text-trust-900">
                      {row.overall}
                    </td>
                    {WEIGHTS.map((w) => (
                      <ScoreCell
                        key={w.key}
                        value={row.scores[w.key]}
                        reversed={w.reversed}
                      />
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className="mt-6 text-xs text-slate-500">
            Full scoring methodology and locked rubric anchors: Documentation/Feature_Scoring_Rubric.xlsx.
            Product data sourced from Documentation/Product Matrix.xlsx.
          </p>
        </div>
      </section>
    </PageShell>
  );
}
